---
title: "Figure 1 Script"
output: html_notebook
---

This script makes Fig. 1, the methods figure. 

```{r}
library(ggplot2)
```

```{r}
data <- read.csv("~/Desktop/GitHub/MsCcHSFeed/Data/fig1data.csv", header = TRUE)
```

Create df with labels/annotations for each facet

```{r}
fig1labels <- data.frame(
  label = c("")
)
```



Let's graph it! 

```{r}
fig1 <- ggplot(data = data, aes(x = day, y = temp, group = HS, color = outcome)) + 
  theme_bw() + 
  facet_wrap(facets = "para", nrow = 2, ncol = 1) + 
  geom_line() + 
  ylim(22, 42) + 
  labs(x = "Day since molt to 3rd instar", y = "Rearing Temperature (C)") + 
  scale_x_continuous(breaks = seq(1, 8, 1), labels = c("0", "1", "2", "10", "11", "12", "25", "26"), limits = c(0.75, 8)) + 
  scale_color_manual(values = c("#1E88E5", "lime green", "#D81B60")) + 
  theme(strip.background = element_blank(), strip.text = element_blank()) +
  theme(legend.position = "none")
  

fig1
```

I will add annotations in powerpoint because doing so with facet_wrap is a nightmare! 

```{r}
ggsave(filename = "~/Desktop/GitHub/MsCcHSFeed/Figs/Fig1Manuscript.png", plot = fig1, width = 8, height = 5)
```

